### ISSUE TITLE
Telegram 实例创建导致的 GetMe 请求失败后导致的程序意外退出[无法签到]

### ISSUE THREAD

**Issue by Esonhugh** [Potat0000/HealthCheckin#2]
可能存在的修复方案 Connect 函数内容 移动到 Send 中的头部

**Comment by Esonhugh** [comment]
建议看看另一个有没有类似的问题（（（

**Comment by Potat0000** [comment]
尝试 [v3](https://github.com/Potat0000/HealthCheckin/releases/tag/v3)

**Comment by Esonhugh** [comment]
v3 修复完成 存在记录
